title: Parvat Sapkota # your name (or website title) here
logo: "/images/pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I like to solve problems, code, and am interested in the business side of things. Using the available data to find insights, analyze, predict or make recommendations to businesses excites me.
  <br><br>
  <a href="https://www.linkedin.com/in/parvat-sapkota-839ab8191/">LinkedIn</a> 
  <a href="https://github.com/parvatsapkota">GitHub</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
